### ISSUE TITLE
Accepting wrong email id

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#1]
Signed up using <abc@yahoo.com>

**Comment by Mythri295** [comment]
When I signed up with wrong email id - it is not showing the user <name>, but accepted the sign up with wrong email id.
![screen shot 2018-12-03 at 11 14 50 pm](https://user-images.githubusercontent.com/30720308/49391306-47929300-f751-11e8-813c-c10c80bfecc4.png)

**Comment by Mythri295** [comment]
![screen shot 2018-12-03 at 11 19 34 pm](https://user-images.githubusercontent.com/30720308/49391546-f46d1000-f751-11e8-88ea-1f733aded1b2.png)

**Comment by amit-choudhary** [comment]
@Mythri295 We won't work on this for now. It's fine. We can add confirmation email later and then we will see how it progresses.
