### ISSUE TITLE
Expert connect <Job seeker Signin>

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#101]
Please remove the dropdown icon for expert connect as a job seeker has only one option.

![Screen Shot 2019-07-23 at 1 13 10 PM](https://user-images.githubusercontent.com/30720308/61693065-81e68a00-ad4c-11e9-9daa-c4413d784341.png)

Also, replace the text as below

Existing text -Choose how to connect
new text - Message

Existing text - Mail
New text - Ask your question!

**Comment by lvlnsiva** [comment]
changes done
