### ISSUE TITLE
Text to be replaced

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#106]
when the user submits the contact form, please use the below text.

Thanks for your message! We'll get back to you shortly.

we see the below text now, replace the text as shown above.

![Screen Shot 2019-07-23 at 2 40 12 PM](https://user-images.githubusercontent.com/30720308/61699229-1efaf000-ad58-11e9-8997-95bd5e122c4e.png)

**Comment by lvlnsiva** [comment]
Fixed
