### ISSUE TITLE
Landing page text for Employers

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#107]
![Screen Shot 2019-07-23 at 2 45 35 PM](https://user-images.githubusercontent.com/30720308/61699493-a183af80-ad58-11e9-8883-cf3deb81e9f2.png)

you see the text is repeated twice. pls change and update as below :

Wanna talk to our recruitment experts?
<CTA Contact us form>

**Comment by lvlnsiva** [comment]
Fixed
