### ISSUE TITLE
Unpublish  job action CTA  for employer signed in

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#109]
Please add the below CTA 

![Screen Shot 2019-07-23 at 4 08 46 PM](https://user-images.githubusercontent.com/30720308/61705837-3d66e880-ad64-11e9-8f55-47ea033bcf7a.png)

Below company logo and name - we need to add **<Unpublish this job>**

The flow will be - once the user clicks unpublish - the job should be deleted.

**Comment by lvlnsiva** [comment]
Enhancement Done

**Comment by Mythri295** [comment]
Can we just show a message on the top
Congratulations! you just unpublished this job.

**Comment by Mythri295** [comment]
@lvlnsiva  pls add this text
