### ISSUE TITLE
Text replace for signed in employer

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#110]
Please replace the below existing with the new one shared

![Screen Shot 2019-07-23 at 4 18 16 PM](https://user-images.githubusercontent.com/30720308/61706351-83707c00-ad65-11e9-8c8d-ab55563e9eb4.png)
 
**Existing -** 
Apply to top startups jobs with just one click
Don’t settle for less, find your dream job

**New -**
Write an impressive job headline and attract top talent.
We'll match best candidates with our auto source tools

**Comment by lvlnsiva** [comment]
Fixed
