### ISSUE TITLE
Text replace <Hiring stories> for signed in employer

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#111]
![Screen Shot 2019-07-25 at 4 40 34 PM](https://user-images.githubusercontent.com/30720308/61870136-fc550c80-aefa-11e9-8543-bd3f991bfa10.png)

Existing :  
Stay up to date with our startup stories
Learn about the hiring process, Company benefits and more!

New : 
Attract talent crafting impressive stories!
The one and the only platform to offer brand stories next to your jobs.

Same to be updated on the landing page of employers when they navigate to hiring stories.

**Comment by lvlnsiva** [comment]
Fixed
