### ISSUE TITLE
expert connect message 

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#118]
![Screen Shot 2019-09-09 at 8 35 37 PM](https://user-images.githubusercontent.com/30720308/64542607-7a516380-d341-11e9-8a28-02fee5407cbf.png)

**Comment by Mythri295** [comment]
As discussed, when I am clicking on <send message> am getting the below error message.

**Comment by lvlnsiva** [comment]
Its working fine for me in live also, in both places I tested.

**Comment by lvlnsiva** [comment]
Please check once again

**Comment by lvlnsiva** [comment]
Please send me the credentials of that particular user
