### ISSUE TITLE
Text alignment -Job posting 

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#121]
pls review the below and align the text box
![Screen Shot 2019-09-22 at 8 53 24 AM](https://user-images.githubusercontent.com/30720308/65381829-91675c80-dd16-11e9-8c73-11b99e074eb5.png)

**Comment by Mythri295** [comment]
@lvlnsiva 

Pls fix this as a priority as it's not allowing me to post if the text limit is more

**Comment by sushmitha-k** [comment]
fixed
