### ISSUE TITLE
Editor (Job posting page)

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#123]
I don't see all the options in the editor

![Screen Shot 2019-09-22 at 9 02 04 AM](https://user-images.githubusercontent.com/30720308/65381890-038c7100-dd18-11e9-8b6b-4500848faa49.png)

**Comment by sushmitha-k** [comment]
As I checked we are allowing only these ['underline', 'anchor', 'h2', 'h3', 'quote'] options in the editor
