### ISSUE TITLE
drop down(remove the drop down)

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#124]
Pls remove the drop-down icon from the jobs listing page as this feature is not functional.

![Screen Shot 2019-09-22 at 9 25 53 AM](https://user-images.githubusercontent.com/30720308/65385271-6e56a000-dd4a-11e9-9918-36b6eaa742b9.png)

**Comment by lvlnsiva** [comment]
In local its not coming

**Comment by Mythri295** [comment]
@sushmitha-k  I think this was design thing, can you see if we can change this?

**Comment by sushmitha-k** [comment]
fixed
