### ISSUE TITLE
Hyperlink 

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#125]
![Screen Shot 2019-09-22 at 3 10 48 PM](https://user-images.githubusercontent.com/30720308/65385335-4156bd00-dd4b-11e9-829d-ff0cc6ddd80e.png)

**Comment by Mythri295** [comment]
You can see the hyperlink is active on Location as well, which is not needed. pls remove where it is not required.

**Comment by lvlnsiva** [comment]
Fixed
