### ISSUE TITLE
Alignment issue <url -https://www.skillpad.co/jobs/11

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#126]
https://www.skillpad.co/jobs/11

I see the alignment is messed up completely.
@sushmitha-k  pls fix this asap.
![Screen Shot 2019-09-25 at 9 07 36 PM](https://user-images.githubusercontent.com/30720308/65616419-a3782200-dfd8-11e9-936f-b7c90c6c42d6.png)

**Comment by sushmitha-k** [comment]
fixed
