### ISSUE TITLE
logo preview for job seeker

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#127]
I think we need to set the preview image dimensions for company logo. 

@sushmitha-k @lvlnsiva Can you look into this pls
![Screen Shot 2019-09-25 at 9 40 13 PM](https://user-images.githubusercontent.com/30720308/65619187-5a769c80-dfdd-11e9-9c3c-40cd495288db.png)

**Comment by lvlnsiva** [comment]
Please prepare one document for all the new enhancements, so that i can work on them

**Comment by sushmitha-k** [comment]
fixed
