### ISSUE TITLE
Post jobs CTA for registered user

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#133]
When the employer signs up and clicks on post jobs for free, nothing is happening.

Pls, direct them to post job page when the signed up user clicks post jobs for free.

![Screen Shot 2019-10-02 at 2 04 03 PM](https://user-images.githubusercontent.com/30720308/66029732-803ffc00-e51d-11e9-9d48-68c7b8627b9b.png)

**Comment by lvlnsiva** [comment]
This is enhancement not an issue

**Comment by Mythri295** [comment]
@lvlnsiva it's redirecting to employer profile page, I asked to redirect to the job post page.
