### ISSUE TITLE
Google sign in

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#14]
I tried signing in using my google account.
got the below error message 

![screen shot 2018-12-03 at 11 56 55 pm](https://user-images.githubusercontent.com/30720308/49393439-3e0c2980-f757-11e8-8aec-7568ef5f43ef.png)

**Comment by amit-choudhary** [comment]
@Mythri295 This is working for me. Can you please try again?

**Comment by Mythri295** [comment]
I am getting the same error.

**Comment by Mythri295** [comment]
I am still getting the same message when I tried signing with google.
