### ISSUE TITLE
User Profile <Expert board>

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#18]
I haven't added any experts on my expert board. It should show <view expert list button> if I haven't added any experts. currently, it is showing the experts in my account. 

Steps :
Logged in using Google account
click on my "my account"
the user sees - Applied jobs, Expert board, and My stories. Applied jobs & My stories are showing the right options - Find more jobs & find more stories. But Expert board is showing the below experts which I haven't added.  It should show "Find more experts".

<button find more experts> is not working.

![screen shot 2018-12-06 at 3 37 10 pm](https://user-images.githubusercontent.com/30720308/49577196-e6dfa200-f96c-11e8-991c-42e89cae224c.png)

**Comment by Shruti2791** [comment]
Here its just a static page.
