### ISSUE TITLE
Sign in using Facebook

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#19]
![screen shot 2018-12-06 at 3 39 36 pm](https://user-images.githubusercontent.com/30720308/49577376-42aa2b00-f96d-11e8-993d-9abf6a874480.png)

Getting this message.

**Comment by amit-choudhary** [comment]
Resolved.

**Comment by Mythri295** [comment]
I could sign in using the FB id, but looks like the UI is completely deviant after I sign in.  pls take a look at the screen below 

![screen shot 2019-01-15 at 1 13 27 pm](https://user-images.githubusercontent.com/30720308/51165853-8dea1e80-18c7-11e9-9426-733f9468fa36.png)

**Comment by Mythri295** [comment]
I am able to replicate this issue if am using FB as Sign in mode.

When I sign in with google & log out and sign in again with FB, it is authenticating.
