### ISSUE TITLE
Linkedin sign in using wrong PW

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#20]
Signed in using Linkedin - gave a wrong pw.

Error message is not in sync with the GUI.

![screen shot 2018-12-06 at 3 50 58 pm](https://user-images.githubusercontent.com/30720308/49578167-1c858a80-f96f-11e8-8745-38ab25fb228c.png)

**Comment by amit-choudhary** [comment]
Duplicate of https://github.com/SkillPad/Fixit/issues/13
