### ISSUE TITLE
Admin Panel - Unable to create job keywords

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#25]
![screen shot 2019-01-08 at 2 41 30 pm](https://user-images.githubusercontent.com/30720308/50820790-971d3d80-1353-11e9-8836-8eec852100a9.png)
![screen shot 2019-01-07 at 5 43 48 pm](https://user-images.githubusercontent.com/30720308/50820801-a603f000-1353-11e9-8f18-7f18c10d8c51.png)

**Comment by amit-choudhary** [comment]
This must be done.
