### ISSUE TITLE
UI alignment to be fixed per design

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#36]
the current view is 
![Screen Shot 2019-03-10 at 10 56 37 PM](https://user-images.githubusercontent.com/30720308/54088799-d41fa380-4387-11e9-843c-9fdf35c784ba.png)

Actual should be 
![Screen Shot 2019-03-10 at 10 58 04 PM](https://user-images.githubusercontent.com/30720308/54088816-ffa28e00-4387-11e9-945d-cfae3e578fba.png)

**Comment by lvlnsiva** [comment]
Fixed
