### ISSUE TITLE
Expert board <show more> button is not working

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#5]
![screen shot 2018-12-03 at 11 04 58 pm](https://user-images.githubusercontent.com/30720308/49390883-20879180-f750-11e8-8dd2-7c86d6601c5d.png)

**Comment by Shruti2791** [comment]
We are hiding this functionality for now, from everywhere on the website, because we won't be having a lot of content initially. We'll add it later when the page load would become slow because of excessive content.
