### ISSUE TITLE
Not able to see hiring stories under employer profile

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#58]
I am unable to see the hiring stories of the specific employee.

I posted a hiring story for the employer account -Wizely. I don't see this is getting captured when I sign into the employer account.

![Screen Shot 2019-05-07 at 7 07 43 PM](https://user-images.githubusercontent.com/30720308/57303666-6ed3fe80-70fb-11e9-9960-49d6a4a1a03c.png)

**Comment by lvlnsiva** [comment]
Fixed
