### ISSUE TITLE
delete the vertical share icons on hiring stories

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#60]
I still see the vertical share options when I click the hiring story. pls delete the vertical social icons.

![Screen Shot 2019-05-07 at 11 34 31 PM](https://user-images.githubusercontent.com/30720308/57322461-31826780-7121-11e9-96f8-95ff8d8b7ce5.png)

**Comment by lvlnsiva** [comment]
Fixed

**Comment by Mythri295** [comment]
@lvlnsiva I see it's working, but the alignment is completely messed up here.

**Comment by lvlnsiva** [comment]
In Production hiring story show page, the alignment is proper. Please check once again
