### ISSUE TITLE
Job seeker profile tab <My hiring stories>

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#61]
I don't see the condition enabled under my hiring stories in the profile tab. We are able to see the same hiring story twice. we should enable a user to see/ like a hiring story only once. pls see the snapshot.
![Screen Shot 2019-05-07 at 11 39 52 PM](https://user-images.githubusercontent.com/30720308/57322695-c2f1d980-7121-11e9-85c5-f3a55d30f477.png)

**Comment by lvlnsiva** [comment]
This is working fine

**Comment by Mythri295** [comment]
This is not working @lvlnsiva given below are the issues :

1) when I click on Like (heart icon) and unclick it's not showing the same under profile tab -"my stories"
you can see the snapshot below 

![Screen Shot 2019-06-11 at 4 42 50 PM](https://user-images.githubusercontent.com/30720308/59267732-89ecdd80-8c68-11e9-9b23-9d7bfc1b2908.png)

you see only two stories are like by me, but under the profile tab, it's showing me a different.
![Screen Shot 2019-06-11 at 4 43 11 PM](https://user-images.githubusercontent.com/30720308/59267746-940edc00-8c68-11e9-8244-5c9ab8baac4d.png)

**Comment by Mythri295** [comment]
you can see the one liked is not captured at all @lvlnsiva
