### ISSUE TITLE
Jobs CTA under hiring stories

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#62]
When I clicked jobs CTA on Hiring stories, it's taking me to the 

![Screen Shot 2019-05-08 at 12 09 26 AM](https://user-images.githubusercontent.com/30720308/57324581-b5d6e980-7125-11e9-98a2-ba6ee2a8075d.png)

![Screen Shot 2019-04-16 at 6 32 02 PM](https://user-images.githubusercontent.com/30720308/57324472-7c05e300-7125-11e9-9925-b960b7a2d9d1.png)
error page.

**Comment by lvlnsiva** [comment]
Fixed
