### ISSUE TITLE
Sign up & Login page "Error message content" to be replaced

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#64]
1) If the users click submitting empty form for pw field use the below message for specific fields:
Scenario 1:  If the user submits empty pw show the below error message 
![Screen Shot 2019-05-15 at 12 40 20 PM](https://user-images.githubusercontent.com/30720308/57755522-c7fced00-770e-11e9-992d-d3e4794a8b2e.png)

2) If the user submits empty email id field,  show the below content.

**Please enter an email address ** 

**Also, our test message is lasting only for a few seconds, it shouldn't be like that. It should reflect until the user performs a different action on the site,**

**Comment by lvlnsiva** [comment]
Fixed

**Comment by Mythri295** [comment]
I see text messaging is not properly aligned.
I entered wrong pw.
You can see overwriting on the text. Need to fix the text issues

![Screen Shot 2019-07-18 at 2 57 20 PM](https://user-images.githubusercontent.com/30720308/61446205-72da9300-a96c-11e9-8731-e0c723b753c5.png)
