### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#65]
Trying to sign in using Facebook & canceling takes me to the home page.

The right flow should be - it should bring the user to sign in page.

**Comment by lvlnsiva** [comment]
Fixed

**Comment by Mythri295** [comment]
Am getting the below error msg when I signed in with FB.

![Screen Shot 2019-06-11 at 4 33 25 PM](https://user-images.githubusercontent.com/30720308/59267001-ac7df700-8c66-11e9-9b34-cf4c25cb8058.png)
