### ISSUE TITLE
Social Media icons on home page are not activated

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#67]
![Screen Shot 2019-05-17 at 12 37 47 PM](https://user-images.githubusercontent.com/30720308/57909531-ac295080-78a0-11e9-9b81-b2a13fd009c1.png)

**Comment by lvlnsiva** [comment]
This is one is not an issue need to implement.

**Comment by Mythri295** [comment]
@lvlnsiva we need to align with the links, as the plan is to finish all the tasks by the end of the month.

here are the links 
https://www.linkedin.com/company/skillpad-co/
https://www.facebook.com/SkillPad-310795763075604/?modal=admin_todo_tour
https://twitter.com/SkillpadC

**Comment by lvlnsiva** [comment]
Just need to provide links for the icons??

**Comment by Mythri295** [comment]
yes

**Comment by lvlnsiva** [comment]
Fixed

**Comment by Mythri295** [comment]
@lvlnsiva these social media links should open in separate tabs. pls fix this.

**Comment by lvlnsiva** [comment]
Fixed pls check
