### ISSUE TITLE
My expert page connect button is not working

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#7]
![screen shot 2018-12-03 at 11 20 58 pm](https://user-images.githubusercontent.com/30720308/49391619-31d19d80-f752-11e8-9f4b-3b250f8a3989.png)

**Comment by Mythri295** [comment]
Also, no images and remove button is not clickable.

**Comment by Mythri295** [comment]
![screen shot 2018-12-03 at 11 22 59 pm](https://user-images.githubusercontent.com/30720308/49391714-6f362b00-f752-11e8-9825-d2402f241051.png)
Find more experts button is not working

**Comment by Shruti2791** [comment]
This page is yet to be integrated with dynamic content. The content seen on the page right now is static.
