### ISSUE TITLE
Experience tab -Profile page

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#71]
It's accepting the text as well when I typed abcd in experience tab was not shown any error message.

We need to restrict the input type to number for this field and also should show a clear error message.

error message
Please enter valid experience (eg. 3)

**Comment by lvlnsiva** [comment]
Fixed Please check

**Comment by Mythri295** [comment]
It's still accepting text, please see the preview. we need to show the error message if the user enters text characters. @lvlnsiva can you please make sure a clear error message is shown.
![Screen Shot 2019-06-08 at 10 00 17 AM](https://user-images.githubusercontent.com/30720308/59142001-7de8ed80-89d4-11e9-8b06-280de60006dd.png)

**Comment by Mythri295** [comment]
I am not able to see any error message also when I enter the text characters and click on Save button.

**Comment by lvlnsiva** [comment]
I fixed the issue its working for me in production also for my login
