### ISSUE TITLE
Job posting from Admin panel

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#76]
I don't see location string is getting captured when I post the job from Admin panel.

Also, once the job is posted, while there is an option to edit but when I click on edit it is giving me a screen whose fields are different
**Below is the screen showing me option to edit :**

![Screen Shot 2019-05-25 at 6 00 25 PM](https://user-images.githubusercontent.com/30720308/58369424-c524a800-7f17-11e9-947b-2657ef7a2f38.png)

Screen After I click edit
![Screen Shot 2019-05-25 at 6 06 33 PM](https://user-images.githubusercontent.com/30720308/58369450-0e74f780-7f18-11e9-8465-e0d6796b1473.png)

**Comment by lvlnsiva** [comment]
Its working fine, please update and check once
