### ISSUE TITLE
job seeker Profile view - Employer notification

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#77]
@lvlnsiva We need to hide the below two fields while showing job seeker profile view for employer.

one . - Profile image (hide this field from employer profile view)
![Screen Shot 2019-05-25 at 6 18 38 PM](https://user-images.githubusercontent.com/30720308/58369548-94457280-7f19-11e9-8d2b-f36ccd9d8a75.png)

two: Save button should be also hidden from employer view. It doesn't make any sense for the employer to view Save.
![Screen Shot 2019-05-25 at 6 18 47 PM](https://user-images.githubusercontent.com/30720308/58369556-b2ab6e00-7f19-11e9-9dab-377500f7052a.png)

**Comment by lvlnsiva** [comment]
Fixed
