### ISSUE TITLE
Jobs CTA on Hiring stories

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#78]
@lvlnsiva When I click jobs CTA on hiring stories, it's taking me to the error page.

![Screen Shot 2019-05-26 at 7 57 48 AM](https://user-images.githubusercontent.com/30720308/58376604-fdfe6480-7f8b-11e9-9695-d215e481e62f.png)

**Comment by lvlnsiva** [comment]
Fixed
