### ISSUE TITLE
Founder dairies- share button is not working

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#8]

**Comment by Mythri295** [comment]
I see two FB icons added in the share button.

![screen shot 2019-01-08 at 2 43 33 pm](https://user-images.githubusercontent.com/30720308/50821013-1a3e9380-1354-11e9-912b-c4cf9c134661.png)

**Comment by amit-choudhary** [comment]
@Shruti2791 remove duplicate facebook links.

**Comment by amit-choudhary** [comment]
Picking this up.

**Comment by amit-choudhary** [comment]
@Mythri295 Please verify this.
