### ISSUE TITLE
Hiring stories <Profile Tab>

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#80]
The hiring stories liked by the user should be a clickable link. I don't see it's clickable now. 
Clicking this should take them to the page of complete hiring story.
![Screen Shot 2019-06-11 at 5 02 32 PM](https://user-images.githubusercontent.com/30720308/59268755-07b1e880-8c6b-11e9-9022-631d7fde6d63.png)

**Comment by lvlnsiva** [comment]
Fixed

**Comment by Mythri295** [comment]
@lvlnsiva No, it's not working

**Comment by lvlnsiva** [comment]
Its working fine for me. Please check once

**Comment by Mythri295** [comment]
@lvlnsiva it's not working for me.
![Screen Shot 2019-06-20 at 3 48 59 PM](https://user-images.githubusercontent.com/30720308/59841895-f6579300-9372-11e9-9007-9699c22ddb94.png)


This is not clickable now.

**Comment by lvlnsiva** [comment]
please provide me the login details for the same

**Comment by lvlnsiva** [comment]
![Screen Shot 2019-06-20 at 11 00 34 PM](https://user-images.githubusercontent.com/5269744/59868992-dabead80-93af-11e9-99d0-23660f1138a7.png)

**Comment by lvlnsiva** [comment]
In production also its working for me
