### ISSUE TITLE
email notifications <SETTINGS PAGE> 

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#81]
When I click on email notifications tick tab and click **update**, it's asking me to enter new PW.

These two are different functionalities and shouldn't be mixed up.

Why are we asking to enter pw for clicking on update button for email notifications?
![Screen Shot 2019-06-14 at 4 58 55 PM](https://user-images.githubusercontent.com/30720308/59506412-bfdacd80-8ec5-11e9-80c1-b1d7309f570f.png)

**Comment by lvlnsiva** [comment]
Fixed
