### ISSUE TITLE
Search icon click is not activated.

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#86]
![Screen Shot 2019-07-06 at 10 36 10 PM](https://user-images.githubusercontent.com/30720308/60759186-8ae21680-a03e-11e9-95eb-03d47c393829.png)

**Comment by Mythri295** [comment]
@lvlnsiva icon is not activated on hiring stories, expert board and jobs

**Comment by lvlnsiva** [comment]
Fixed
