### ISSUE TITLE
Text for search with no matching results

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#88]
Please show the below text if no matching results are found :

Jobs : No matching jobs found.
Hiring stories: we are sorry, we don't have any matching results to your search.
Expert board : we are sorry, we don't have any matching results to your search.

**Comment by lvlnsiva** [comment]
Fixed

**Comment by lvlnsiva** [comment]
![Screen Shot 2019-08-03 at 8 48 47 PM](https://user-images.githubusercontent.com/5269744/62413777-8bb39b80-b630-11e9-9d0a-27ceb4d2cbb1.png)
![Screen Shot 2019-08-03 at 8 49 42 PM](https://user-images.githubusercontent.com/5269744/62413778-8bb39b80-b630-11e9-9245-b1c00ab1ac5e.png)
![Screen Shot 2019-08-03 at 8 49 59 PM](https://user-images.githubusercontent.com/5269744/62413779-8bb39b80-b630-11e9-81cc-dc7ac7a1531f.png)
