### ISSUE TITLE
Text to be updated.

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#93]
Please existing text to below. (Once the user confirms the link and signs in, pls show the below text)

**current text :** 

![Screen Shot 2019-07-18 at 1 12 34 PM](https://user-images.githubusercontent.com/30720308/61438804-ede87d00-a95d-11e9-869a-c3f7f77286f7.png)

New text 
Congratulations! your account is active now. Create an amazing profile :)

**Comment by lvlnsiva** [comment]
Fixed
