### ISSUE TITLE
Jobseeker profile

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#94]
We need to show the right messages for the below actions performed by user 

When the user hovers to my stories,jobs, experts on profile tab 

 User didn't add any hiring stories but hovers to my stories - show the below msg

Like a story, you didn't like any yet.
You didn't apply to any jobs
Connect to experts now, no connects now.

**Comment by lvlnsiva** [comment]
This is not an issue enhancement

**Comment by lvlnsiva** [comment]
Need some clarity on this, please add UI image so that It will be easy
