### ISSUE TITLE
get updates tab on landing page

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#96]
I see this is not activated.

![Screen Shot 2019-07-18 at 3 28 33 PM](https://user-images.githubusercontent.com/30720308/61448572-c058ff00-a970-11e9-9689-755c4d542a90.png)

We can automatically them to our sengrid list and whenever a new hiring story/job posted we can send a notification email

**Comment by lvlnsiva** [comment]
Its not active from starting, its an enhancement not an issue
