### ISSUE TITLE
Job seeker profile tab 

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#98]
**Pls fix this issue, this is repeating many times** @

When I click on my stories, jobs, and expert on the profile tab, am seeing the below error message.
![Screen Shot 2019-07-23 at 12 06 48 PM](https://user-images.githubusercontent.com/30720308/61688454-afc6d100-ad42-11e9-9fb1-57d0e0f20950.png)

**Comment by lvlnsiva** [comment]
Its working
